// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!WOVQPOOOVQPO'#C^OOQO'#Ce'#CeOOQO'#Ca'#CaQVQPOOO_QPO,58xOOQO-E6_-E6_OjQPO1G.dOOQO7+$O7+$O",
  stateData: "r~OWOS~OSQOYPO~OSQOYPOZVO~ORWO~ORS~",
  goto: "qYPPZPPaPPPkXQOPSTQSOQTPTUSTXROPST",
  nodeNames: "⚠ File Group Number Word",
  maxTerm: 11,
  nodeProps: [
    ["group", -2,2,4,"Expression"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "%]~RdX^!apq!axy#Uyz#Z}!O#`!O!P$l!P!Q#}!Q![$l!c!}#}#O#P#}#R#S#}#T#o#}#y#z!a$f$g!a#BY#BZ!a$IS$I_!a$I|$JO!a$JT$JU!a$KV$KW!a&FU&FV!a~!fYW~X^!apq!a#y#z!a$f$g!a#BY#BZ!a$IS$I_!a$I|$JO!a$JT$JU!a$KV$KW!a&FU&FV!a~#ZOY~~#`OZ~~#eWS~}!O#}!O!P$l!P!Q#}!Q![$l!c!}#}#O#P#}#R#S#}#T#o#}~$SWS~}!O#}!O!P#}!P!Q#}!Q![#}!c!}#}#O#P#}#R#S#}#T#o#}~$sWR~S~}!O#}!O!P$l!P!Q#}!Q![$l!c!}#}#O#P#}#R#S#}#T#o#}",
  tokenizers: [0],
  topRules: {"File":[0,1]},
  tokenPrec: 31
})
